on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Hello world action step
        uses: ./.github/custom-actions/sourcehub-layer