name: ConaIsa

# Relevant to events - https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows
on: 
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]
    paths:
    - '**.sh'

jobs:
  # Linting
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installing dependencies..
        run: if ! apt list --installed | grep -qP ".*shellcheck.*"; then apt install -y shellcheck; fi
      - name: Linting..
        run: for file in $(git --no-pager diff --name-only origin/master | grep -o ".*\.sh") ;do shellcheck --external-sources --shell=sh "$file";done