# Workflow for vlang
name: ConaIsa

# Relevant to events - https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows
on: 
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]
    paths:
    - '**.v'

jobs:
  # Kernel specific builds
  build-vlang:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: building..
        run: make build-vlang

  # Docker builds
  build-vlang-debian:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://debian/testing:latest
      - uses: actions/checkout@v2
      - name: building..
        run: make build-vlang

  build-vlang-fedora:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://fedora/latest:latest
      - uses: actions/checkout@v2
      - name: building..
        run: make build-vlang

  # Run tests
  check-vlang:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-18.04]
    steps:
      - uses: actions/checkout@v2
      - name: running tests..
        run: make check-vlang

  # Benchmarks
  bench-vlang:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-18.04]
    steps:
      - uses: actions/checkout@v2
      - name: running benchmarks..
        run: make bench-vlang